Models/Computer.cs
namespace ComputerShop.Models
{
    public class Computer
    {
        public int ID { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Description { get; set; } =   string.Empty ;
        public float Price { get; set; }

        public Computer_Comp computer_Comp = new Computer_Comp();
    }
}

Models/Computer_Comp.cs
namespace ComputerShop.Models
{
    public class Computer_Comp
    {
        public string Ram { get; set; } = string.Empty;
        public string CPU { get; set; } =   string.Empty ;
        public string MotherBoard { get; set; } = string.Empty;
        public string GrapicCard { get; set; } = string.Empty;
    }
}

Models/ErrorViewModel.cs
namespace ComputerShop.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ComputerController.cs
using ComputerShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace ComputerShop.Controllers
{
    public class ComputerController : Controller
    {

        public   List<Computer> AllComputer = new List<Computer>();

        public void addComputers ()
        {
            for (int i =0; i< 10; i++)
            {
                Computer computer = new Computer();
                computer.ID = i;
                computer.Name = i.ToString();
                computer.Description = i.ToString();
                computer.Price = 18;
                computer.computer_Comp.CPU = i.ToString();
                computer.computer_Comp.Ram = "RAm";
                computer.computer_Comp.MotherBoard = i.ToString();
                AllComputer.Add(computer);   
            }
        }

        public ComputerController ()
        {
            addComputers ();
        }

        public IActionResult Index()
        {
            return View(AllComputer);
        }

        public IActionResult Details(int ID)
        {
             Computer c = AllComputer.FirstOrDefault(o => o.ID == ID); 
              
            return View(new ComputerDetailsVM(){
                ID = c.ID,
                Ram = c.computer_Comp.Ram
            });
        }

    }
}

Controllers/HomeController.cs
using ComputerShop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ComputerShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Computer/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ComputerDetailsVM
@Model.ID
@Model.Ram

Views/Computer/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@



@model List<Computer>

<h2>All Computers</h2>
 
<table class="table">
<thead>
<tr>
<th>Description</th>
<th>Price</th>
<th>Details</th>
</tr>
</thead>
<tbody>

@foreach (var computer in Model)
{
<tr>
<td>@computer.Description</td>
<td>@computer.Price</td>
<td><a href="@Url.Action("Details", "Computer", new { ID = computer.ID })">View Details</a></td>
</tr>       
        }
</tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ComputerShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ComputerShop.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ComputerShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ComputerShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>